### ISSUE TITLE
examples files for three distribution files

### ISSUE THREAD

**Issue by maiziex** [BGI-Qingdao/stLFR_reads_sim#1]
Hi, 
I am using stLFRSim to simulate stlfr reads. For the three distribution files, you give an illustration to show it. However I am wondering can you provide three example distribution files, like basing on some empirical distribution that user can use them first.   
It's hard for user to make these files from scratch. 
Thanks for helping me with this~
Best
Maizie

**Comment by cchd0001** [comment]
update in https://github.com/BGI-Qingdao/stLFR_reads_sim/tree/master/example
